### ISSUE TITLE
SimulationAgent fails if the machine's timezone is not set to UTC +00:00

### ISSUE THREAD

**Issue by janakiramm** [Azure/device-simulation-dotnet#149]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Simulation agent throws the error "The UTC time represented when the offset is applied must be between year 0 and 10,000" 

# Steps to reproduce 

1. Configure the storage adapter by adding DocDB connection string and make sure it is working
2. Configure device simulation agent by adding IoT Hub connection string
3. Stop the device simulation agent container in the VM deployed as a part remote monitoring resource group
4. Run the device simulation project locally 

# Expected behavior 
Telemetry should be sent from the local simulation agent

# Current behavior 
The simulation agent fails with error "The UTC time represented when the offset is applied must be between year 0 and 10,000"
# Known workarounds 

Set the timezone of the Windows machine to London/Dublin to reflect UTC +00:00

# Context and Environment
* Operating System: Windows 10
* GitHub branch: ...
* .NET Runtime: .NET Core 1.x and .NET Framework
* IDE - VS 2017

**Comment by Dolphinsimon** [comment]
The problem is one of the property of class Device named lastStatusUpdated has a default value {0001/1/1 0:00:00}, and its type is DateTimeOffset.  It fails because the date is outside the range allowed. new DateTimeOffset(DateTime.MinValue) will fail on any computer with a timezone that is ahead of UTC (positive offset), and new DateTimeOffset(DateTime.MaxValue) will fail on any computer with a timezone that is behind UTC (negative offset).

**Comment by Dolphinsimon** [comment]
You can solve this problem by:
1.Changing the property to DateTime. Simple but might have other problems.
2.Converting the DateTimeKind from Unspecified to UniversalTime.
