### ISSUE TITLE
Where i can get complete code for device simulation with Web application?

### ISSUE THREAD

**Issue by ashuthinks** [Azure/device-simulation-dotnet#271]
Where i can get complete code for device simulation with Web application?
I have created my custom applcation but difficult to use Web service. 
Can anyone help me to get all complete code so that it will be helpful to me for customization ?

**Comment by peterfelts** [comment]
Hi there, there are multiple microservices that make up device simulation. At a minimum, you'll need device simulation, the storage adapter, and the web UI to run the simulation code locally. It won't be completely local, of course, because you'll still need an IoT Hub and other services to run locally. 

What problems are you having with the web service, specifically?

Here are the repositories that you'll need:

- https://github.com/Azure/device-simulation-dotnet/
- https://github.com/Azure/pcs-simulation-webui
- https://github.com/Azure/pcs-storage-adapter-dotnet

Let me know if we're missing anything in our documentation or if the documentation isn't clear enough.
