### ISSUE TITLE
Device Simulator is not working

### ISSUE THREAD

**Issue by ajaichemmanam** [Azure/device-simulation-dotnet#315]
# Type of issue 

- [X ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
I am trying to run the Remote monitoring solution locally. I created all required azure resources using the pcs script. All environment variables were set. I ran the webui and the remote monitoring services dotnet project. The webui is working fine but shows no data available. I tried to clone the device simulation dotnet and ran it using visual studio. I again set all the required environment variables except 

PCS_TWIN_READ_WRITE_ENABLED
PCS_WEBUI_AUTH_AAD_TENANT
PCS_AAD_SECRET
They are not in launchSettings.json file. Don't know what I should do there

"PCS_VMSS_NAME" which mentions about a VM scaling. As I am running it locally, I hope it's not required. 

The project builds succesfully and runs. and http://localhost:9003/v1/status shows this

{"Name":"DeviceSimulation","Status":"OK:Alive and well","CurrentTime":"2018-11-15T07:23:47+00:00","StartTime":"2018-11-15T07:17:44+00:00","UpTime":363,"UID":"WebService.31435652-5f87-4ca4-8b16-774571893677","Properties":{"SimulationRunning":"false","PreprovisionedIoTHub":"true"},"Dependencies":{"Storage":"OK:Alive and well","PreprovisionedIoTHub":"OK"},"$metadata":{"$type":"Status;1","$uri":"/v1/status"}}

See attached log. 
But no devices are added to the iot hub and no messages are sent to it. when I checked cosmosdb

I can see CosmosDb has main, nodes, simulations created in it. main and nodes has some data written in it. But simulations document is empty. 

Since some documents are written into the cosmos, I think its not related to the connection string etc. 

The Next way I tried to run is through docker. I ran docker-compose up in devicesimulator scripts folder.

But shows the following error
[ERROR][2018-11-15 07:38:07.263][WebService.f30eac8e-0e9e-406a-8518-3e36770337f3][HttpClient:SendAsync] Request failed, {"timeSpentMsecs":10007,"Method":"GET","Uri":"http://storageadapter:9022/v1/collections/simulations/values","Message":"A task was canceled. The request timed out, the endpoint might be unreachable.","e":{"ExceptionFullName":"System.Threading.Tasks.TaskCanceledException","ExceptionMessage":"A task was canceled.","StackTrace":"   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\n   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Http.HttpClient.<SendAsync>d__9.MoveNext() in /home/azureiotpcs/vsts-agent/_work/46/s/Services/Http/HttpClient.cs:line 92","Source":"System.Private.CoreLib","Data":{},"InnerException":null}}

What's happening? Any help is appreciated.

# Expected behavior 
Sent the simulation datas to the iot hub and refletcs in cosmos as well as webui

# Current behavior <!-- The actual behavior observed --
Simulation data is not sent

# Context and Environment
* Operating System: Windows 10 Pro
* GitHub branch: ...
* .NET Runtime: ...

[log-devicesimulation.txt](https://github.com/Azure/device-simulation-dotnet/files/2584157/log-devicesimulation.txt)

```

**Comment by murdockcrc** [comment]
Be aware that the device simulator .net project has environment variables predefined in the Visual Studio project itself (Properties -> Debug). So even if you have the env vars in your local host (via `SETX` command), you need to remove the env var placeholders in the Visual Studio project.

**Comment by ajaichemmanam** [comment]
@murdockcrc 
Thanks for your time. 
I have all the environment variables set properly except PCS_SUBSCRIPTION_DOMAIN, PCS_WEBUI_AUTH_AAD_TENANT, PCS_AAD_SECRET, PCS_TWIN_READ_WRITE_ENABLED,
PCS_VMSS_NAME

Please give more details on what to give for these. I am running the service locally in visual studio. 

Also regrading the new status api changes, please review this change and update.

device-simulation/Services/StorageAdapter/StorageAdapterClient.cs Line69
status = data["Status"].ToString().StartsWith("OK:");
changed to
status = data["Status"].ToString().Contains("true");
for complying with the new status API changes.

When running the simulator, with default simulation. New devices are provisioned in the iothub and is reflecting in the dashboard also. But none of the devices are online/ Sending telemetry data. So now I am using a c# simulator coded by myself. But due to the dashboard dependencies, I am forced to run this also. Please fix the telemetry part in this project

**Comment by tommo-ms** [comment]
@ajaichemmanam - I wanted to know if you are still seeing this issue after merging latest changes from master?  If so, let us know if you have a Partitions table in CosmosDb and if the devices that are registered in the Hub are having twin properties updated. If you could also send latest debug logs that would help. 

Thanks,
-Tom

**Comment by ajaichemmanam** [comment]
Yes, The Simulator is still not runnning as expected. In cosmosDb, I couldn't see a Partitions table in it. In the devicesimulation database, There are 3 colections, simulations, nodes, main. Simulations collection is empty. nodes contain 1 file

{
    "Data": "",
    "ExpirationUtcMsecs": 1548242191856,
    "LastModifiedUtcMsecs": 1548242131856,
    "LockOwnerId": "",
    "LockOwnerType": "",
    "LockExpirationUtcMsecs": -1,
    "id": "7c938284a8a24442b18b34e14e1cf755.2019-01-23T09:40:42",
    "_rid": "QdwCAOJsHnsCAAAAAAAAAA==",
    "_self": "dbs/QdwCAA==/colls/QdwCAOJsHns=/docs/QdwCAOJsHnsCAAAAAAAAAA==/",
    "_etag": "\"00001693-0000-0000-0000-5c484cd30000\"",
    "_attachments": "attachments/",
    "_ts": 1548242131
}

Main contains Seed Completed & Master Node
{
    "Data": "Seed Completed",
    "ExpirationUtcMsecs": -1,
    "LastModifiedUtcMsecs": 1548058378334,
    "LockOwnerId": "",
    "LockOwnerType": "",
    "LockExpirationUtcMsecs": -1,
    "id": "SeedCompleted",
    "_rid": "QdwCAO9HAJIBAAAAAAAAAA==",
    "_self": "dbs/QdwCAA==/colls/QdwCAO9HAJI=/docs/QdwCAO9HAJIBAAAAAAAAAA==/",
    "_etag": "\"0a002f2d-0000-0000-0000-5c457f080000\"",
    "_attachments": "attachments/",
    "_ts": 1548058376
}

{
    "Data": "Record locked by the master node",
    "ExpirationUtcMsecs": -1,
    "LastModifiedUtcMsecs": 1548242132640,
    "LockOwnerId": "7c938284a8a24442b18b34e14e1cf755.2019-01-23T09:40:42",
    "LockOwnerType": "Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Clustering.ClusterNodes",
    "LockExpirationUtcMsecs": 1548242252640,
    "id": "MasterNode",
    "_rid": "QdwCAO9HAJICAAAAAAAAAA==",
    "_self": "dbs/QdwCAA==/colls/QdwCAO9HAJI=/docs/QdwCAO9HAJICAAAAAAAAAA==/",
    "_etag": "\"0b00ca03-0000-0000-0000-5c484cd40000\"",
    "_attachments": "attachments/",
    "_ts": 1548242132
}

**Comment by peterfelts** [comment]
Here are some thoughts/questions:

1. Remote Monitoring doesn't use the latest version of Device Simulation. They use version 1.0.3, which is referenced through a docker tag "DS-1.0.3" as can be seen [here](https://github.com/Azure/pcs-cli/blob/68e5283443a7d6693ef7a544013a5ca0a4351d92/solutions/remotemonitoring/single-vm/docker-compose.dotnet.yml#L69). It's possible that if you cloned the device-simulation-dotnet repository locally, that you're using master, which might not be set up to work properly with the version of Remote Monitoring that you're using. You might want to sync your local repository to the DS-1.0.3 tag, so that the version of Simulation that you're running is the same version that Remote Monitoring is expecting (I'm assuming that you're using Remote Monitoring from master).

2. The fact that there is no data in the Simulation storage nor the partitions table tells me that no simulation has started. The service is reporting that it's running, so either it hasn't been asked to create a simulation (something is blocking the communication between the web UI and the Simulation service, or the default simulations haven't been set up to run), or something else is going on in the Simulation service.

2.1. There are default simulations that can be configured in Device Simulation, and Remote Monitoring uses this functionality to start a simulation by default (see [here](https://github.com/Azure/device-simulation-dotnet/blob/master/Services/data/templates/remote-monitoring-simulations-template.json)). It's possible that a missing configuration/environment variable is preventing Simulation from knowing that it should start the default Simulation. See PCS_SEED_TEMPLATE [here](https://github.com/Azure/pcs-cli/blob/68e5283443a7d6693ef7a544013a5ca0a4351d92/solutions/remotemonitoring/single-vm/docker-compose.dotnet.yml#L93). You mentioned that all required variables are set. Check to make sure that you don't have settings in launchSettings.json that could conflict with environment variables, in case you're using environment variables. 

3. What happens when you query the service directly to start a simulation, [through the REST API](https://github.com/Azure/device-simulation-dotnet/blob/master/docs/API_SPECS_SIMULATIONS.md)?
