### ISSUE TITLE
Question: Updating state and properties.

### ISSUE THREAD

**Issue by TechPreacher** [Azure/device-simulation-dotnet#370]
I have set up a test with a custom device type. Validation of the JSON and JS files are OK. The test runs and I can see messages being sent to IoT Hub.

I am trying to update the state and the properties. Can I do that from device-state.js by calling both updateState and updateProperties in the function main?

```
function main(context, previousState, previousProperties) {
    restoreSimulation(previousState, previousProperties);

    // Update state
    state.something = newValue;
    updateState(state);
    log("Updated state to: " + state.something);

    // Update Lifetime property
    properties.Lifetime++;
    updateProperty(properties)
    log("Updated properties to: "+properties.Lifetime);
}
```

I am using the log() function but I cannot find any logs after a successful run. I hope this isn't FAQ but I looked for the answers and found nothing in this direction...

Thanks!

**Comment by wildengineer** [comment]
@TechPreacher I had the same issue. Turn on Debug using these instructions

https://github.com/Azure/device-simulation-dotnet/wiki/Simulation-Service-Developer-Reference-Guide#changing-the-log-level

**Comment by peterfelts** [comment]
You should be able to call both updateState and updateProperty from the JS code.

Simulation uses a JS interpreter package (Jint) in order to run the device script. This package supports mapping calls to C# backed functions from JS code. In order to make sure that you can call a C# backed function from the JS code, you'll need to provide some a mapping to the function... I think the way to do that is with the following comment-looking line in the JS file:

/*global updateProperty*/

You'll need one of those lines for each C# function that you're going to call. Also, if you're going to introduce a new C#-backed method call, you can reference this:

https://github.com/Azure/device-simulation-dotnet/blob/942b2d55938d12f2d591c831ae476afa64d38c40/Services/Simulation/JavascriptInterpreter.cs#L73

Perhaps the methods you're calling aren't mapped in your JS code?

**Comment by peterfelts** [comment]
Closing this. Please reactivate if the suggestions in my previous comment didn't work.
