### ISSUE TITLE
Verify that custom device models can be loaded from Windows and MacOS disk paths

### ISSUE THREAD

**Issue by dluc** [Azure/device-simulation-dotnet#84]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Description 

Since it's possible to define the path for loading custom device models, the feature should work across platforms, e.g. regardless of the path separator ("/" vs "\")

**Comment by scout208** [comment]
I added a custom device model, "Lightbulb", and I'm not seeing it in the device models returned by calling the /devicemodels endpoint from the REST API. Is this related to this issue?

**Comment by dluc** [comment]
Hi @scout208, the issue above should not affect your test.

Did you follow [this tutorial](https://docs.microsoft.com/azure/iot-suite/iot-suite-remote-monitoring-test) to setup the custom device model, including the note *Configure the project to copy the new Lightbulb device files to the output directory* ?

Could you provide some information about the location of the files, and how you start the web service?

**Comment by scout208** [comment]
Yeah, @dluc, that tutorial was the one I was trying to follow. I'm not sure how to configure the project to copy the Lightbulb device files to the output directory. The tutorial wasn't very clear on that. I did set the "Copy to output directory" property to "Always if newer" in Visual Studio, but I was running the microservice with Docker, so I didn't think that would really matter. 

As far as the files locations, I have lightbulb-01.json in the Services/data/devicemodels folder:

![image](https://user-images.githubusercontent.com/9426329/32663750-a530ff40-c5f4-11e7-817e-21b9ca2f938a.png)

I have the lightbulb-01-state.js, SwitchOff-method.js, and SwitchOn-methods.js files in the Services/data/decivemodels/scripts folder:

![image](https://user-images.githubusercontent.com/9426329/32663810-e28330ca-c5f4-11e7-9ef9-4426de96b0e1.png)

I've been starting the web service using Docker. I tried using Visual Studio, but I kept getting an error because the rate was set to 0 which was below the MIN_RATE and I wasn't sure how to change it.

**Comment by timlaverty** [comment]
@scout208 If using VS, you'll need to add the files to the project and set them to Copy if Newer or Always Copy:
![image](https://user-images.githubusercontent.com/5084013/32671954-34ec2b92-c5fe-11e7-8fc5-fd24e8cba0c3.png)

Once you've done this you should be able to rebuild the docker container with those files in place.  You could also update the docker-compose yaml file to mount a folder with the model files in it if you don't want to rebuild the code.  

The other thing I'd suggest is running in VS (or other IDE) instead of docker while debugging.  You can step through the code and also it's easier to see the logs than running with docker and pulling the logs with docker logs <container>.

For MIN_RATE - the only place this is in the code is a constant:
        private const double MIN_RATE = 1;
Can you provide more info on the failure you're seeing?

@dominicbetts Can we update the walkthrough with the copy always/copy if newer missing step?

**Comment by scout208** [comment]
@timlaverty, okay, like I said, I did set those properties to "Copy if newer" in Visual Studio. I don't understand how that has any effect on running the project with docker though, cause I thought those are two different build processes.

As far as the VS error, here it is:

![image](https://user-images.githubusercontent.com/9426329/32672700-ae0357ea-c611-11e7-943a-5cdcf54b975a.png)

Let me know if I can help provide you anymore info.
